### ISSUE TITLE
doesnt work with ksp 1.12.2

### ISSUE THREAD

**Issue by georgegohl888** [linuxgurugamer/ksp-advanced-flybywire#37]
no matter what ive tried i cannt get it to work with the latest ksp. Very annoying as my controller wont work with vanilla ksp. I dont know if there are any logs that will help? let me know how to get 'em, and ill send 'em.

**Comment by linuxgurugamer** [comment]
First off, please direct support requests to the forum
Second, since you didn't tell me anything, I can't help.  And that includes log file.  Instructions for getting the log are available on the forum, just look at any post of mine, the link is in the signature
Third, it does work for me, so pretty sure it's just an install issue, but will look for a post on the forums
